# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wig_calc_interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from main import *
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 689)
        MainWindow.setStatusTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wigner_grid_frame = QtWidgets.QFrame(self.tab)
        self.wigner_grid_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.wigner_grid_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.wigner_grid_frame.setObjectName("wigner_grid_frame")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.wigner_grid_frame)
        #self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 491, 581))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        #self.widget = QtWidgets.QWidget(self.verticalLayoutWidget_2)

        self.widget = WignerWidget(self.verticalLayoutWidget_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_3.addWidget(self.widget)
        self.verticalLayoutWidget_2.raise_()
        self.gridLayout_2.addWidget(self.wigner_grid_frame, 0, 0, 2, 1)
        self.local_view_frame = QtWidgets.QFrame(self.tab)
        self.local_view_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.local_view_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.local_view_frame.setObjectName("local_view_frame")
        self.gridLayout_2.addWidget(self.local_view_frame, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 15, -1, 15)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_tot_label = QtWidgets.QLabel(self.frame)
        self.line_tot_label.setObjectName("line_tot_label")
        self.verticalLayout.addWidget(self.line_tot_label)
        self.tot_neg_label = QtWidgets.QLabel(self.frame)
        self.tot_neg_label.setObjectName("tot_neg_label")
        self.verticalLayout.addWidget(self.tot_neg_label)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_2.addWidget(self.frame, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.button_random = QtWidgets.QPushButton(self.tab_2)
        self.button_random.setGeometry(QtCore.QRect(40, 60, 211, 41))
        self.button_random.setObjectName("button_random")
        self.p_spinbox = QtWidgets.QSpinBox(self.tab_2)
        self.p_spinbox.setGeometry(QtCore.QRect(60, 30, 61, 27))
        self.p_spinbox.setObjectName("p_spinbox")
        self.n_spinbox = QtWidgets.QSpinBox(self.tab_2)
        self.n_spinbox.setGeometry(QtCore.QRect(160, 30, 61, 27))
        self.n_spinbox.setObjectName("n_spinbox")
        self.button_zero = QtWidgets.QPushButton(self.tab_2)
        self.button_zero.setGeometry(QtCore.QRect(40, 110, 211, 41))
        self.button_zero.setObjectName("button_zero")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(49, 169, 201, 221))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 201))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1020, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wigner Function Calculator"))
        self.line_tot_label.setText(_translate("MainWindow", "Total Along Line:"))
        self.tot_neg_label.setText(_translate("MainWindow", "Total Negativity:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Wigner Function"))
        self.button_random.setText(_translate("MainWindow", "random pure state"))
        self.button_zero.setText(_translate("MainWindow", "zero state"))
        self.label.setText(_translate("MainWindow", "Current State"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Density Matrix"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
